---
    # npm can be used to install current versions of phantomjs. This installs beta
    # version 2.5.0, which comes with new support.
    - name: install libfontconfig1
      become: yes
      apt:
          name: libfontconfig1
          state: present

    - name: install libjpeg8
      become: yes
      apt:
          name: libjpeg8
          state: present

    - name: install libhyphen-dev
      become: yes
      apt:
          name: libhyphen-dev
          state: present

    - name: Check if phantomjs is installed
      command: which phantomjs
      register: which_phantomjs
      failed_when: which_phantomjs.rc > 1
      changed_when: which_phantomjs.rc == 1
      ignore_errors: True

    - name: Make a directory for phantomjs
      become: yes
      file:
          path: /usr/lib/node_modules/phantomjs-prebuilt/
          state: directory
      when: which_phantomjs|changed

    - name: Download phantomjs
      become: yes
      get_url:
          url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz
          dest: /root
      when:  which_phantomjs|changed

    - name: Unarchive phantomjs
      become: yes
      command: tar -zxvf /root/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz --directory /usr/lib/node_modules/phantomjs-prebuilt/ --keep-directory-symlink --preserve-permissions --strip 1
      when: which_phantomjs|changed

    - name: 'Make phantomjs executable'
      file:
          path: /usr/lib/node_modules/phantomjs-prebuilt/bin/phantomjs
          mode: 0755
      when: which_phantomjs|changed

    - name: Symlink the downloaded phantomjs to /usr/bin/phantomjs
      become: yes
      file:
          src: /usr/lib/node_modules/phantomjs-prebuilt/bin/phantomjs
          dest: /usr/bin/phantomjs
          state: link
      when: which_phantomjs|changed

    - name: Remove the downloaded package
      become: yes
      file:
          path: /root/phantomjs-2.5.0-beta-linux-ubuntu-xenial-x86_64.tar.gz
          state: absent
      when: which_phantomjs|changed
