---
- hosts: local

  vars:
    composer_home: '{{ lookup("pipe", "composer -ng config home") }}'

  roles:
    - system
    - lamp
    - node

  tasks:
    - name: run handlers
      meta: flush_handlers

    - name: set git config values
      template:
        src: files/gitconfig.j2
        dest: /home/vagrant/.gitconfig

    - name: change into project directory on login
      lineinfile:
        path: ~/.bashrc
        line: cd /var/www/{{ hostname }}
        state: present
