---
- name: detect email_hostname value
  set_fact:
    email_hostname: '{{ "email." ~ hostname }}'
  when: email_hostname is not defined

- name: download mailhog
  become: yes
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v1.0.0/MailHog_linux_amd64
    dest: /usr/local/bin/mailhog
    force: yes
    mode: 0755

- name: create mailhog service
  become: yes
  template:
    src: ../templates/mailhog.service.j2
    dest: /lib/systemd/system/mailhog.service

- name: ensure mailhog is started
  become: yes
  systemd:
    daemon_reload: yes
    name: mailhog
    state: restarted
    enabled: yes

- name: disable outbound 25 and 587 traffic (just in case)
  become: yes
  ufw:
    rule: deny
    proto: tcp
    port: "{{ item }}"
  with_items:
    - 25
    - 587

- name: ensure 25 and 587 are closed
  wait_for:
    host: 127.0.0.1
    port: "{{ item }}"
    state: stopped
  with_items:
    - 25
    - 587

- name: create virtual host
  include_role:
    name: lamp
    tasks_from: create_vhost
  vars:
    server_name: "{{ email_hostname }}"
    port: 8025
    type: reverse_proxy
    extra: |
      <Location /api/v2/websocket>
        ProxyPass ws://127.0.0.1:8025/api/v2/websocket
      </Location>

  tags:
    - vhost
