---
- name: update apt-cache
  become: yes
  apt:
    update_cache: yes

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zip
    - unzip
    - git
  tags:
    - packages

- name: install additional packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages | default([]) }}"
  tags:
    - packages
