---
- name: install supervisor
  become: yes
  apt:
      name: supervisor
      state: present
  tags:
      - supervisor

- name: ensure supervisor is enabled
  become: yes
  service:
      name: supervisor
      state: started
      enabled: yes
  tags:
      - supervisor
