---
- name: detect desired php version
  set_fact:
    php_version: 7.2
  when: php_version is not defined
  tags:
    - php_modules

- name: set package prefix
  set_fact:
    package_prefix: "php{{ php_version if php_version != 7.2 else '' }}"
  tags:
    - php_modules

- name: add php repo
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes
  when: php_version != 7.2
  tags:
    - php_modules

- name: install php modules
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # Handily copied from https://github.com/webdevops/Dockerfile/blob/master/docker/php/ubuntu-18.04/Dockerfile
    - imagemagick
    - graphicsmagick
    - ghostscript
    - jpegoptim
    - libjpeg-turbo-progs
    - pngcrush
    - optipng
    - apngopt
    - pngnq
    - pngquant
    - "{{ package_prefix }}-cli"
    - "{{ package_prefix }}-fpm"
    - "{{ package_prefix }}-json"
    - "{{ package_prefix }}-intl"
    - "{{ package_prefix }}-curl"
    - "{{ package_prefix }}-mysql"
    - "{{ package_prefix }}-gd"
    - "{{ package_prefix }}-sqlite3"
    - "{{ package_prefix }}-imap"
    - "{{ package_prefix }}-pgsql"
    - "{{ package_prefix }}-ldap"
    - "{{ package_prefix }}-opcache"
    - "{{ package_prefix }}-soap"
    - "{{ package_prefix }}-zip"
    - "{{ package_prefix }}-mbstring"
    - "{{ package_prefix }}-bcmath"
    - "{{ package_prefix }}-xmlrpc"
    - "{{ package_prefix }}-xsl"
    - "{{ package_prefix }}-bz2"
    - php-pear
    - php-apcu
    - php-igbinary
    - php-mongodb
    - php-imagick
    - php-redis
    - php-amqp
    - php-memcached
    - php-xdebug
  tags:
    - php_modules

- name: install additional php modules
  become: yes
  apt:
    name: "{{ package_prefix }}-{{ item }}"
    state: present
  with_items: "{{ php_modules | default([]) }}"
  tags:
    - php_modules

- name: ensure php-fpm is started
  become: yes
  service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes

- name: change php-fpm to listen on socket
  become: yes
  ini_file:
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    section: www
    option: listen
    value: 127.0.0.1:9000

- name: set default timezone
  become: yes
  ini_file:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    section: Date
    option: date.timezone
    value: 'America/New_York'
  notify:
    - restart php

- name: override php settings
  become: yes
  with_items: "{{ php_config | default([]) }}"
  ini_file:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    option: "{{ item.option }}"
    section: "{{ item.section | default('PHP') }}"
    value: "{{ item.value }}"
  notify:
    - restart php
