---
- name: detect desired php version
  set_fact:
    php_version: 7.2
  when: php_version is not defined
  tags:
    - php_modules

- name: add php repo
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes
  when: php_version != 7.2
  tags:
    - php_modules

- name: install php modules
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # Handily copied from https://github.com/webdevops/Dockerfile/blob/master/docker/php/ubuntu-18.04/Dockerfile
    - imagemagick
    - graphicsmagick
    - ghostscript
    - jpegoptim
    - libjpeg-turbo-progs
    - pngcrush
    - optipng
    - apngopt
    - pngnq
    - pngquant
    - php7.2-cli
    - php7.2-fpm
    - php7.2-json
    - php7.2-intl
    - php7.2-curl
    - php7.2-mysql
    - php7.2-gd
    - php7.2-sqlite3
    - php7.2-imap
    - php7.2-pgsql
    - php7.2-ldap
    - php7.2-opcache
    - php7.2-soap
    - php7.2-zip
    - php7.2-mbstring
    - php7.2-bcmath
    - php7.2-xmlrpc
    - php7.2-xsl
    - php7.2-bz2
    - php-pear
    - php-apcu
    - php-igbinary
    - php-mongodb
    - php-imagick
    - php-redis
    - php-amqp
    - php-memcached
    - php-xdebug
  tags:
    - php_modules

- name: install additional php modules
  become: yes
  apt:
    name: "php{{ php_version if php_version != 7.2 else '' }}-{{ item }}"
    state: present
  with_items: "{{ php_modules | default([]) }}"
  tags:
    - php_modules

- name: ensure php-fpm is started
  become: yes
  service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes

- name: change php-fpm to listen on socket
  become: yes
  ini_file:
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    section: www
    option: listen
    value: 127.0.0.1:9000

- name: set default timezone
  become: yes
  ini_file:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    section: Date
    option: date.timezone
    value: 'America/New_York'
  notify:
    - restart php

- name: override php settings
  become: yes
  with_items: "{{ php_config | default([]) }}"
  ini_file:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    option: "{{ item.option }}"
    section: "{{ item.section | default('PHP') }}"
    value: "{{ item.value }}"
  notify:
    - restart php
