---
- name: download minio
  become: yes
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: 0755
  tags:
      - minio

- name: create minio service
  become: yes
  template:
    src: ../templates/minio.service.j2
    dest: /lib/systemd/system/minio.service
  tags:
    - minio

- name: ensure minio is started
  become: yes
  systemd:
    daemon_reload: yes
    name: minio
    state: started
    enabled: yes
  tags:
    - minio

- name: create virtual host
  include_role:
    name: lamp
    tasks_from: create_vhost
  vars:
    server_name: "minio.{{ hostname }}"
    port: 9001
    type: reverse_proxy
  tags:
    - vhost
    - minio
