---
- name: add rabbitmq repo key
  become: yes
  apt_key:
    keyserver: hkps.pool.sks-keyservers.net
    id: '0x6B73A36E6026DFCA'
  tags:
    - rabbitmq

- name: install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https
    state: present
  tags:
    - rabbitmq

- name: Add erlang source list file
  become: yes
  copy:
    dest: "/etc/apt/sources.list.d/bintray.erlang.list"
    content: deb http://dl.bintray.com/rabbitmq-erlang/debian bionic erlang-21.x
  tags:
    - rabbitmq

- name: pin erlang to bintray repo
  become: yes
  copy:
    dest: "/etc/apt/preferences.d/erlang"
    content: |
      Package: erlang*
      Pin: release o=Bintray
      Pin-Priority: 1000
  tags:
    - rabbitmq

- name: install erlang packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - erlang-base
    - erlang-asn1
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl
  tags:
    - rabbitmq

- name: add repository
  become: yes
  copy:
    dest: "/etc/apt/sources.list.d/bintray.rabbitmq.list"
    content: deb https://dl.bintray.com/rabbitmq/debian bionic main
  tags:
    - rabbitmq

- name: create rabbitmq directory
  become: yes
  file:
    path: /etc/rabbitmq
    state: directory

- name: enable management plugin
  become: yes
  copy:
    dest: "/etc/rabbitmq/enabled_plugins"
    content: '[rabbitmq_management].'
  tags:
    - rabbitmq

- name: allow remote guest access
  become: yes
  copy:
    dest: "/etc/rabbitmq/rabbitmq.conf"
    content: 'loopback_users = none'
  tags:
    - rabbitmq

- name: install rabbitmq-server
  become: yes
  apt:
    name: rabbitmq-server
    state: present
    update_cache: yes
  tags:
    - rabbitmq

- name: ensure rabbitmq is started
  become: yes
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  tags:
    - rabbitmq
